Iter13
VadimFilimonov/urlshortener pull request #13
Opened 2023-03-07 15:45 UTC by VadimFilimonov

2023-03-08 00:21 UTC, Perederey requested changes
В целом хорошая работа, но есть критические замечания
1) работа с пакетом contex
2) работа с базой данных 

Давай может быть еще на 1:1 обсудим? Но а целом дал комментарий для всего

2023-03-08 00:21 UTC, Perederey commented on cmd/shortener/main.go
> +	switch {
Я бы сделал бы просто if и в функцию бы код перенес NewStorage, но так тоже нормально

2023-03-08 00:21 UTC, Perederey commented on internal/handler/handler.go
>  		case http.MethodGet:
Вот это нужно убрать, у тебя же есть пакет chi в роутинге которого ты явно указываешь метод

2023-03-08 00:21 UTC, Perederey commented on internal/handler/handler.go
> +				} else if errDataAdd != nil {
От else нужно избавляться, затрудняется чтение кода

2023-03-08 00:21 UTC, Perederey commented on internal/handler/handler.go
> +		input := ShortenInput{}
var input ShortenInput,
Для пустых переменных принято вот так писать

2023-03-08 00:21 UTC, Perederey commented on internal/handler/handler.go
> +		shortenURLPath, errDataAdd := data.Add(input.URL, userIDCookieValue)
Просто err вторым полем

2023-03-08 00:21 UTC, Perederey commented on internal/handler/handler.go
> +		output, err := json.Marshal(ShortenOutput{
Output, input - это слишком общие названия - подумай как лучше назвать 


LongLink, shortLink?

2023-03-08 00:21 UTC, Perederey commented on internal/handler/handler.go
> +		body, err := io.ReadAll(r.Body)
Не закрыл body

2023-03-08 00:21 UTC, Perederey commented on internal/handler/handler.go
> +		ctx, cancel := context.WithTimeout(r.Context(), time.Second*1)
А где ты делаешь обработку context? Надо добавить вызов ctx.Done()

2023-03-08 07:14 UTC, VadimFilimonov commented on internal/handler/handler.go
> +		ctx, cancel := context.WithTimeout(r.Context(), time.Second*1)
Добавил следующей строкой

```
defer ctx.Done()
```

2023-03-08 07:15 UTC, VadimFilimonov commented on internal/handler/handler.go
> +		body, err := io.ReadAll(r.Body)
Добавил следующей строкой

```go
defer r.Body.Close()
```

2023-03-08 07:15 UTC, VadimFilimonov commented on internal/handler/handler.go
> +		input := ShortenInput{}
Поправил

2023-03-08 09:34 UTC, VadimFilimonov commented on internal/handler/handler.go
>  		case http.MethodGet:
Разделил на два хендлера: `NewGet` и `NewPost`

2023-03-08 09:51 UTC, VadimFilimonov commented on internal/handler/handler.go
> +				} else if errDataAdd != nil {
Убрал else

2023-03-08 09:51 UTC, VadimFilimonov commented on cmd/shortener/main.go
> +	switch {
Сделал новую функцию `GetStorage`, в которую просто передаю конфиг, а она уже возвращает подходящую реализацию Storage

2023-03-08 09:56 UTC, VadimFilimonov commented on internal/handler/handler.go
> +		output, err := json.Marshal(ShortenOutput{
> LongLink, shortLink?

Мне не очень нравятся эти имена, так как они не отражают содержимое переменных

2023-03-08 09:56 UTC, VadimFilimonov commented on internal/handler/handler.go
> +		output, err := json.Marshal(ShortenOutput{
Прямо сейчас `input` это структура с одним полем `URL`

```go
type ShortenInput struct {
	URL string `json:"url"`
}
```

`LongLink` это не структура, а скорее поле этой структуры. Когда я читаю "длинная ссылка", то ожидаю, что в ней будет строка, т.е. сама ссылка

2023-03-08 09:58 UTC, VadimFilimonov commented on internal/handler/handler.go
> +		output, err := json.Marshal(ShortenOutput{
Аналогично с `output`, в которой прямо сейчас хранится такая структура

```go
type ShortenOutput struct {
	Result string `json:"result"`
}
```

Не может в `shortLink` храниться объект (это уже в терминах JS), с полем `result`, в котором уже будет сама ссылка

2023-03-08 10:23 UTC, VadimFilimonov commented on internal/handler/handler.go
> +		output, err := json.Marshal(ShortenOutput{
Заменил `input` на `requestBody`, а `output` на `responseJSON`

2023-03-08 10:26 UTC, VadimFilimonov commented on internal/handler/handler.go
> +		shortenURLPath, errDataAdd := data.Add(input.URL, userIDCookieValue)
Тут мне пришлось назвать ошибку иначе, так как ее мне нужно обрабатывать позже:

1. Я получаю `shortenURLPath` и ошибку из storage
2. Использую `Marshal`
3. Обрабатываю ошибку от  `Marshal`
4. И только потом обрабатываю ошибки от `storage`

2023-03-08 10:27 UTC, VadimFilimonov commented on internal/handler/handler.go
> +		shortenURLPath, errDataAdd := data.Add(input.URL, userIDCookieValue)
Если я начну обрабатывать ошибку сразу же, до мне придется вкладывать один `if` в другой, а это уже мене читабельно(

2023-03-13 19:02 UTC, Perederey commented
Context не блокирующий
Но пожалуйста давай сделаем 1:1 по нему

2023-03-13 20:05 UTC, merged