Iter8
VadimFilimonov/urlshortener pull request #8
Opened 2023-02-13 19:25 UTC by VadimFilimonov

2023-02-17 18:15 UTC, Perederey requested changes
В целом отличный PR, но есть несколько важных ошибок, которые нужно исправить.

Описал подробности в комментариях

2023-02-17 18:15 UTC, Perederey commented on cmd/shortener/main.go
>  )
а нужна ли тебе констана? Может быть лучше это дело записать в Config?

2023-02-17 18:15 UTC, Perederey commented on cmd/shortener/main.go
> +}
может быть это доело лучше выделить в отдельный пакет?

2023-02-17 18:15 UTC, Perederey commented on cmd/shortener/main.go
> +		panic(err)
тут лучше вызывать не panic, а log.Fatal

2023-02-17 18:15 UTC, Perederey commented on cmd/shortener/main.go
> +	flag.Parse()
тут немного напутано, может быть лучше flags также записать в пакет и выделить в функцию Parse()?

2023-02-17 18:15 UTC, Perederey commented on cmd/shortener/main.go
> +		body, err := io.ReadAll(gz)
забыл закрыть body

2023-02-17 18:15 UTC, Perederey commented on internal/handler/handler.go
> +		case http.MethodPost:
убрать case, так как у тебя уже и так есть пакет который это все дело проверяет

2023-02-17 18:15 UTC, Perederey commented on internal/handler/handler.go
> +				body, err := io.ReadAll(r.Body)
забыл снова body закрыть)

2023-02-17 18:15 UTC, Perederey commented on internal/handler/handler_test.go
> +			assert.NotEmpty(t, string(bodyResult))
notEmpty это больше workaround, давай проверять json

2023-02-17 18:15 UTC, Perederey commented on internal/storage/storage.go
> +		file, _ := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0777)
Надо использовать 0644, а не 777
777 - это небезопасно, по-факту любой имеет доступ на запись к этому файлу

2023-02-18 12:00 UTC, VadimFilimonov commented on internal/handler/handler_test.go
> +			assert.NotEmpty(t, string(bodyResult))
Не понимаю о каком `json` речь - мне в ответе приходит `text/plain; charset=utf-8`

При этом, создание короткой ссылки происходит через рандомайзер, следовательно я не могу знать какой мне придет ответ
И единственное, что я могу сделать проверить - это что ответ не пустой

2023-02-18 12:20 UTC, VadimFilimonov commented on cmd/shortener/main.go
> +		body, err := io.ReadAll(gz)
разве `defer gz.Close()` не закрывает body?

У самого `body` нет метода Close

Или здесь также нужно это делать через `r.Body.Close()`?

(Чуть подробнее спросил в пачке)

2023-02-19 15:48 UTC, Perederey commented on internal/handler/handler_test.go
> +			assert.NotEmpty(t, string(bodyResult))
Понял тебя, тут тогда все верно, извиняюсь 🙌

2023-02-19 15:49 UTC, Perederey approved these changes
Все отлично!
Спасибо, что внимательно отнесся к правкам и исправил замечания 💪
Код с каждым разом лучше и лучше.

2023-02-20 05:15 UTC, merged